// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Entities;

namespace Portal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181012082507_dev2")]
    partial class dev2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Portal.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = 2L, Name = "Basic" },
                        new { Id = 1L, Name = "Admin" }
                    );
                });

            modelBuilder.Entity("Portal.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login")
                        .HasMaxLength(120);

                    b.Property<string>("Password");

                    b.Property<long>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1L, Login = "admin", Password = "AQAAAAEAACcQAAAAELaDVDFHgyI0nUxJRT5K7JrZVBu6TM4k4+N8x9HQ7BLFpwXeN/jr6zor3wZbcx/GYg==", RoleId = 1L },
                        new { Id = 2L, Login = "user", Password = "AQAAAAEAACcQAAAAEId5LaM9Xq/DsKwF+zrUS5cuFhLlDgfmACknwSYw9r4mKN+mB/RjCBe8qEuS0+hJrQ==", RoleId = 2L }
                    );
                });

            modelBuilder.Entity("Portal.Entities.User", b =>
                {
                    b.HasOne("Portal.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
